export const SOURCE_REPOSITORIES = [
  {
    slug: "openclaw-openclaw",
    name: "openclaw",
    author: "openclaw",
    sourceUrl: "https://agent-skills.cc/skills/openclaw-openclaw",
    description: "Your own personal AI assistant. Any OS. Any Platform. The lobster way.",
    rating: 157597,
  },
  {
    slug: "composiohq-awesome-claude-skills",
    name: "awesome-claude-skills",
    author: "ComposioHQ",
    sourceUrl: "https://agent-skills.cc/skills/composiohq-awesome-claude-skills",
    description: "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows",
    rating: 30904,
  },
  {
    slug: "astrbotdevs-astrbot",
    name: "astrbot",
    author: "AstrBotDevs",
    sourceUrl: "https://agent-skills.cc/skills/astrbotdevs-astrbot",
    description: "Agentic IM Chatbot infrastructure that integrates lots of IM platforms, LLMs, plugins and AI features.",
    rating: 15529,
  },
  {
    slug: "kepano-obsidian-skills",
    name: "obsidian-skills",
    author: "kepano",
    sourceUrl: "https://agent-skills.cc/skills/kepano-obsidian-skills",
    description: "Agent skills for Obsidian",
    rating: 9029,
  },
  {
    slug: "voltagent-awesome-openclaw-skills",
    name: "awesome-openclaw-skills",
    author: "VoltAgent",
    sourceUrl: "https://agent-skills.cc/skills/voltagent-awesome-openclaw-skills",
    description: "The awesome collection of OpenClaw Skills.",
    rating: 7881,
  },
  {
    slug: "cloudflare-moltworker",
    name: "moltworker",
    author: "cloudflare",
    sourceUrl: "https://agent-skills.cc/skills/cloudflare-moltworker",
    description: "Run OpenClaw on Cloudflare Workers",
    rating: 7451,
  },
  {
    slug: "travisvn-awesome-claude-skills",
    name: "awesome-claude-skills",
    author: "travisvn",
    sourceUrl: "https://agent-skills.cc/skills/travisvn-awesome-claude-skills",
    description: "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows — particularly Claude Code",
    rating: 6125,
  },
  {
    slug: "nevamind-ai-memu",
    name: "ai-memu",
    author: "NevaMind-AI",
    sourceUrl: "https://agent-skills.cc/skills/nevamind-ai-memu",
    description: "Memory for 24/7 proactive agents like openclaw.",
    rating: 5321,
  },
  {
    slug: "zhayujie-bot-on-anything",
    name: "bot-on-anything",
    author: "zhayujie",
    sourceUrl: "https://agent-skills.cc/skills/zhayujie-bot-on-anything",
    description: "A large model-based chatbot builder that can quickly integrate AI models into various software applications.",
    rating: 4173,
  },
  {
    slug: "x-cmd-x-cmd",
    name: "cmd-x-cmd",
    author: "x-cmd",
    sourceUrl: "https://agent-skills.cc/skills/x-cmd-x-cmd",
    description: "Best Buddy for AI Agents like Claude Code. Bootstrap 1000+ command line tools in seconds.",
    rating: 3968,
  },
  // Discovered related sources
  {
    slug: "upstash-context7",
    name: "context7",
    author: "upstash",
    sourceUrl: "https://agent-skills.cc/skills/upstash-context7",
    description: "Context7 MCP Server — Up-to-date code documentation for LLMs and AI code editors",
    rating: 42032,
  },
  {
    slug: "anthropics-skills",
    name: "skills",
    author: "anthropics",
    sourceUrl: "https://agent-skills.cc/skills/anthropics-skills",
    description: "Public repository for Agent Skills",
    rating: 56673,
  },
  {
    slug: "anthropics-claude-code",
    name: "claude-code",
    author: "anthropics",
    sourceUrl: "https://agent-skills.cc/skills/anthropics-claude-code",
    description: "Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster.",
    rating: 56749,
  },
  {
    slug: "f-awesome-chatgpt-prompts",
    name: "awesome-chatgpt-prompts",
    author: "f",
    sourceUrl: "https://agent-skills.cc/skills/f-awesome-chatgpt-prompts",
    description: "Share, discover, and collect prompts from the community. Free and open source.",
    rating: 142366,
  },
  {
    slug: "affaan-m-everything-claude-code",
    name: "everything-claude-code",
    author: "affaan-m",
    sourceUrl: "https://agent-skills.cc/skills/affaan-m-everything-claude-code",
    description: "Complete Claude Code configuration collection — agents, skills, hooks, commands, rules, MCPs.",
    rating: 33322,
  },
  {
    slug: "obra-superpowers",
    name: "superpowers",
    author: "obra",
    sourceUrl: "https://agent-skills.cc/skills/obra-superpowers",
    description: "An agentic skills framework & software development methodology that works.",
    rating: 45537,
  },
  {
    slug: "ruvnet-claude-flow",
    name: "claude-flow",
    author: "ruvnet",
    sourceUrl: "https://agent-skills.cc/skills/ruvnet-claude-flow",
    description: "The leading agent orchestration platform for Claude. Deploy intelligent multi-agent swarms.",
    rating: 13159,
  },
  {
    slug: "yamadashy-repomix",
    name: "repomix",
    author: "yamadashy",
    sourceUrl: "https://agent-skills.cc/skills/yamadashy-repomix",
    description: "Packs your entire repository into a single, AI-friendly file. Perfect for feeding your codebase to LLMs.",
    rating: 21222,
  },
  {
    slug: "campfirein-cipher",
    name: "cipher",
    author: "campfirein",
    sourceUrl: "https://agent-skills.cc/skills/campfirein-cipher",
    description: "Byterover Cipher is an opensource memory layer for coding agents.",
    rating: 3436,
  },
  {
    slug: "x1xhlol-system-prompts-and-models-of-ai-tools",
    name: "system-prompts-and-models-of-ai-tools",
    author: "x1xhlol",
    sourceUrl: "https://agent-skills.cc/skills/x1xhlol-system-prompts-and-models-of-ai-tools",
    description: "FULL system prompts, internal tools & AI models for 30+ AI coding tools.",
    rating: 108357,
  },
  {
    slug: "nextlevelbuilder-ui-ux-pro-max-skill",
    name: "ui-ux-pro-max-skill",
    author: "nextlevelbuilder",
    sourceUrl: "https://agent-skills.cc/skills/nextlevelbuilder-ui-ux-pro-max-skill",
    description: "AI SKILL for building professional UI/UX on multiple platforms.",
    rating: 24362,
  },
  {
    slug: "mixedbread-ai-mgrep",
    name: "mgrep",
    author: "mixedbread-ai",
    sourceUrl: "https://agent-skills.cc/skills/mixedbread-ai-mgrep",
    description: "A calm, CLI-native way to semantically grep everything — code, images, PDFs, and more.",
    rating: 2768,
  },
  {
    slug: "wshobson-agents",
    name: "agents",
    author: "wshobson",
    sourceUrl: "https://agent-skills.cc/skills/wshobson-agents",
    description: "Intelligent automation and multi-agent orchestration for Claude Code.",
    rating: 27122,
  },
  {
    slug: "mattbx-shadcn-skills",
    name: "shadcn-skills",
    author: "mattbx",
    sourceUrl: "https://agent-skills.cc/skills/mattbx-shadcn-skills",
    description: "Skills for building better shadcn/ui apps. Discover 1,500+ existing components.",
    rating: 3000,
  },
  {
    slug: "rocccccc-hub-ued-copilot",
    name: "ued-copilot",
    author: "Rocccccc-hub",
    sourceUrl: "https://agent-skills.cc/skills/rocccccc-hub-ued-copilot",
    description: "AI-powered UI/UX design auditor based on Apple HIG, Material Design, Nielsen Heuristics & WCAG.",
    rating: 2500,
  },
  {
    slug: "flexonze-claude-init",
    name: "claude-init",
    author: "Flexonze",
    sourceUrl: "https://agent-skills.cc/skills/flexonze-claude-init",
    description: "Automatically generate Claude Code configs tailored for your project.",
    rating: 2200,
  },
  {
    slug: "peeperfrog-peeperfrog-create",
    name: "peeperfrog-create",
    author: "PeeperFrog",
    sourceUrl: "https://agent-skills.cc/skills/peeperfrog-peeperfrog-create",
    description: "MCP servers and Claude Skills for AI image generation and LinkedIn posting.",
    rating: 1800,
  },
  {
    slug: "rightbrainai-claude-code-skills",
    name: "claude-code-skills",
    author: "RightbrainAI",
    sourceUrl: "https://agent-skills.cc/skills/rightbrainai-claude-code-skills",
    description: "Official Claude Code skills for Rightbrain AI — create, run, and manage AI tasks.",
    rating: 2100,
  },
  {
    slug: "kakermanis-claudeskill-auth0clis",
    name: "ClaudeSkill_Auth0CLIs",
    author: "kakermanis",
    sourceUrl: "https://agent-skills.cc/skills/kakermanis-claudeskill-auth0clis",
    description: "Claude skill for Auth0 CLI, Deploy CLI, MCP, and secure credential management.",
    rating: 1500,
  },
] as const;

export const CATEGORIES = [
  { slug: "coding", name: "Coding", description: "Code generation, refactoring, and development tools" },
  { slug: "workflow-automation", name: "Workflow Automation", description: "Task automation and process orchestration" },
  { slug: "chatbot", name: "Chatbot", description: "Conversational AI and chatbot platforms" },
  { slug: "memory", name: "Memory", description: "Agent memory, context persistence, and state management" },
  { slug: "devops", name: "DevOps", description: "Deployment, infrastructure, and CI/CD" },
  { slug: "documentation", name: "Documentation", description: "Docs generation, knowledge bases, and README tools" },
  { slug: "knowledge-management", name: "Knowledge Management", description: "Note-taking, PKM, and knowledge graph tools" },
  { slug: "cloud-platform", name: "Cloud/Platform", description: "Cloud deployment, serverless, and platform tools" },
  { slug: "cli-tooling", name: "CLI/Tooling", description: "Command-line tools and terminal utilities" },
  { slug: "multi-agent", name: "Multi-Agent", description: "Multi-agent orchestration and coordination" },
  { slug: "skills-collection", name: "Skills Collection", description: "Curated collections of agent skills and resources" },
  { slug: "integration", name: "Integration", description: "Platform and service integrations" },
] as const;

export const SCORING_WEIGHTS = {
  lexical: 0.30,
  semantic: 0.40,
  category: 0.15,
  popularity: 0.10,
  exactMatch: 0.05,
} as const;

export const SCORING_WEIGHTS_NO_SEMANTIC = {
  lexical: 0.55,
  semantic: 0.00,
  category: 0.25,
  popularity: 0.12,
  exactMatch: 0.08,
} as const;
